// Generated by CoffeeScript 1.9.1
module.exports = function(robot) {
  var d, hour;
  robot.hear(/おはよう/i, function(msg) {
    if (hour < 12) {
      return msg.send("おはよう！早起きは三文の得！");
    } else if (hour >= 12) {
      return msg.send("おそよう！今日も一日頑張るぞい！");
    }
  });
  robot.adapter.on('connected', function() {
    return robot.send({
      room: 'hubot-dev'
    }, "再起動中… あとでスクリプト読み込んでね");
  });
  d = new Date;
  return hour = d.getHours();
};
