// Generated by CoffeeScript 1.9.1
module.exports = function(robot) {
  robot.hear(/おはよう/i, function(msg) {
    var d, hour, str;
    d = new Date;
    hour = d.getHours();
    str = hour + "時";
    return msg.send(str);
  });
  return robot.adapter.on('connected', function() {
    return robot.send({
      room: 'hubot-dev'
    }, "再起動中… あとでスクリプト読み込んでね");
  });
};
